INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-9', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-10', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-16', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-17', 'Mexico (Chiapas, Tabasco)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-19', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-818', 'Mexico (Hidalgo, Querétaro, San Luis Potosí)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-20', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-21', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-632', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-22', 'Mexico (Oaxaca, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-374', 'Mexico (Hidalgo, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-24', 'Mexico (Querétaro, San Luis Potosí)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-25', 'Honduras (Atlántida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-26', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-29', 'Mexico (Tamaulipas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-30', 'Mexico (Hidalgo, Querétaro, San Luis Potosí, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-32', 'Guatemala (Huehuetenango, San Marcos), Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-33', 'Mexico (?Puebla, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-35', 'Mexico (San Luis Potosí)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-36', 'Mexico (Chiapas, Tabasco, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-37', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-38', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-39', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-40', 'Mexico (Chiapas, Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-41', 'Belize (Cayo, Stann Creek, Toledo), Guatemala (Alta Verapaz, Petén, Quiché, Huehuetenango, Izabal), Mexico (Chiapas, Oaxaca, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-42', 'Mexico (Hidalgo, Querétaro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-43', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-817', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-793', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-814', 'Mexico (Puebla)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-44', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-45', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-46', 'Mexico (San Luis Potosí)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-47', 'Mexico (Chiapas, Tabasco)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-52', 'Vietnam (Da Nang)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-54', 'Philippines (Palawan - cult.)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-55', 'Australia (Northern Territory, Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-56', 'India (Kerala)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-57', 'Indonesia (Papua), Papua New Guinea (West Sepik, Morobe)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-58', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-59', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-60', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-574', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-61', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-62', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-63', 'Australia (Queensland [Badu and Moa Islands])', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-829', 'China (Guangxi)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-65', 'China (Guangxi), Vietnam (Lang Son, Quang Ninh, Thai Nguyen, Vinh Phuc)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-66', 'Australia (WA)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-67', 'India (Andhra Pradesh)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-69', 'China (Guangxi), Vietnam (Cao Bang, Lang Son, Tuyen Quang)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-70', 'Papua New Guinea (Bougainville, New Britain), Solomon Islands', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-71', 'Vietnam (Bac Kan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-73', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-75', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-76', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-77', 'Papua New Guinea (Central, Gulf)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-79', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-80', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-81', 'Malaysia (Johor)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-83', 'Thailand (Chantaburi)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-85', 'China (Hainan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-665', 'China (Yunnan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-86', 'Vietnam (Ha Tinh, Nghe An, Quang Binh, Quang Tri)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-87', 'India (Andra Pradesh, Karnataka, Kerala, Maharashtra, Tamil Nadu)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-107', 'Cambodia, Malaysia (Kedah, Perak, Selangor), Thailand (Chumphon, Narathiwat, Phangnga, Phuket, Prachin Buri, Rayong, Ranong, Trang), Vietnam (An Giang, Kien Giang)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-109', 'Vietnam (Son La)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-110', 'Vietnam (Ba Ria-Vung Tau)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-111', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-112', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-114', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-115', 'Philippines (Palawan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-116', 'China (Guangxi)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-117', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-118', 'China (Yunnan), ?N Vietnam', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-820', 'Australia (Qld)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-119', 'China (Guangxi, Yunnan), ?Laos, Vietnam (Bac Kan, Cao Bang, Ha Giang, Hoa Binh, Lai Chau, Lao Cai, Ninh Binh, Son La, Thai Nguyen, Thanh Hoa, Tuyen Quang)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-120', 'Indonesia (Bali, Bengkulu, Jawa
Barat, Jawa Tengah, Jawa Timur,
Lampung, Riau, Sumatra Utara),
Malaysia (Johore, Langkawi,
Malacca, Pahang, Perak, Sabah,
Sarawak, Terengganu), Myanmar,
Philippines (Balabac, Basilan,
Cebu, Masbate, Mindanao,
Mindoro, Negros, Palawan, Panay,
Polillo), Singapore (Changi), Thailand
(Chumphon, Narathiwat,
Phang Nga, Phu Ket, Satun, Trang,
Trat), Vietnam (Kien Giang)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-121', 'Thailand (Chaiyaphum)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-122', 'Vietnam (Binh Dinh, Khanh Hoa, Ninh Thuan, Phu Yen, Quang Ngai)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-123', 'China (Guangdong)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-124', 'Indonesia (Sulawesi Selatan, Sulawesi Tenggara)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-125', 'China (Guangxi), Vietnam (Lang Son, Thai Nguyen)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-126', 'Vietnam (Phu Tho)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-127', 'Australia (WA)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-128', 'East Timor, Indonesia (Nusa Tenggara Timur [Sumba Barat, Sumba Timur, Timur Barat])', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-133', 'China (Guangxi, Guizhou, Yunnan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-134', 'China (Hainan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-136', 'Vietnam (Ha Nam, Ha Tay, Hoa Binh, Ninh Binh)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-137', 'China (Yunnan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-140', 'India (Karnataka)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-141', 'Laos (Khammouan), Vietnam (Da Nang, Dong Nai, Khanh Hoa, Quang Nam)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-142', 'Indonesia (Jawa Barat, Jawa Tengah, Jawa Timur)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-145', 'Philippines (Davao Oriental)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-146', 'Australia (WA)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-653', 'Laos (Khammouan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-147', 'Vietnam (Ba Ria-Vung Tau, Binh Thuan, Khanh Hoa, Ninh Thuan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-154', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-155', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-575', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-156', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-157', 'Laos (Vientiane), Malaysia (Kelantan, Pahang, Terengganu), Thailand (Chantaburi, Chumphon, Narathiwat, Ranong)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-159', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-160', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-161', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-576', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-162', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-163', 'Laos (Champasak, Saravan), Vietnam (Dac Lak, Gia Lai, Kon Tum)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-165', 'Guam, Micronesia (Yap), Northern Mariana Islands (Rota), Palau', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-167', 'Indonesia (Nusa Tenggara Timur)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-169', 'China (Yunnan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-170', 'China (Yunnan), Vietnam (Yen Bai)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-172', 'India (Tamil Nadu), N Sri Lanka', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-674', 'India (Odisha)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-173', 'Philippines (Albay, Cagayan, Quezon, Northern Samar)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-174', 'Laos (Vientiane), Thailand (Nakhon Sawan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-176', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-177', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-673', 'India (Odisha)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-178', 'Vietnam (Binh Thuan, Ninh Thuan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-180', 'China (Sichuan, Yunnan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-181', 'Indonesia (Papua), Papua New Guinea (Western)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-183', 'Bangladesh, Bhutan, China (Yunnan), India (Assam, Manipur, Meghalaya, Sikkim, West Bengal), Laos, Myanmar, Nepal, Thailand (Chiang Mai, Kanchanaburi, Mae Hong Son, Phetchabun, Phrae, Sukhothai), Vietnam (Binh Dinh, Gia Lai, Kon Tum, Lam Dong, Ninh Thuan, Phu Yen, Quang Nam, Quang Ngai)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-186', 'Laos (Vientiane),Thailand (Loei)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-187', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-188', 'Thailand (Prachuap Khiri Khan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-189', 'Australia (Northern Territory, WA)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-191', 'China (Fujian), Japan (Ryukyu Islands)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-196', 'Philippines (Bataan, Batanes, Batangas, Cagayan, Cavite, Isabela, Laguna, Pampanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-197', 'Australia (Ashmore Reef, Christmas Island) Indonesia (Jawa Timur, Kalimantan Barat, Maluku, Papua, Sulawesi Utara, Sulawesi Tengah, Sulawesi Selatan, West Papu), Papua New Guinea (West Sepik).', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-595', 'India (Andaman and Nicobar Islands Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-202', 'Philippines (Misamis Oriental)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-203', 'Philippines (Palawan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-204', 'Papua New Guinea (Eastern Highlands, Madang, Morobe)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-205', 'Australia (Queensland [Murray Island]), Indonesia (Papua, Maluku, Papua Barat), Papua New Guinea (Central, Gulf, Milne Bay, Western)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-206', 'Fiji, New Caledonia, Tonga, Vanuatu', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-207', 'China (Guangxi, Guizhou, Yunnan), ?N Vietnam', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-208', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-815', 'India (Andhra Pradesh)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-210', 'China (Guangxi), Vietnam (Cao Bang, Ninh Binh, Thanh Hoa)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-211', 'China (Hainan Island)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-213', 'Cambodia, Laos (Champasak, Saravan), Myanmar, Thailand (Chachoengsao, Chaiyaphum, Chon Buri, Kanchanaburi, Lampang, Nakhon Ratchasima, Phetchabun, Ratchaburi, Sakon Nakhon, Tak, Uthai Thani, Uttaridit), Vietnam (Dac Lak, Gia Lai, Kon Tum, Nghe An, Tha', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-215', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-216', 'China (Yunnan), Laos (Saravan), ?Myanmar, Thailand (Chiang Mai, Loei, Mae Hong Song, Phrae), Vietnam (Quang Tri)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-217', 'India (Andhra Pradesh, Karnataka, Odisha, Tamil Nadu)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-219', 'Indonesia (Nusa Tenggara Timur)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-221', 'China (Fujian)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-577', 'China (Fujian)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-223', 'China (Taiwan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-224', 'China (Fujian, Guangdong)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-225', 'China (Yunnan), ?Vietnam (Lai Chau)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-226', 'Thailand (Saraburi)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-227', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-228', 'Comoros, Kenya, Madagascar, Mozambique, Seychelles, Tanzania', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-230', 'Vietnam (Hai Phong, Quang Ninh)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-232', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-234', 'Philippines (Cebu, Iloilo, Leyte, Marinduque, Mindoro Oriental, Negros Oriental, Samar)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-235', 'Philippines (Palawan)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-238', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-239', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-240', 'Philippines (Zambales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-241', 'India (Andaman and Nicobar Islands), S Sri Lanka', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-244', 'Mexico (Nuevo León, Tamaulipas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-245', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-246', 'Mexico (Oaxaca, Puebla)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-247', 'Mexico (Oaxaca, Puebla)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-248', 'Mexico (Hidalgo, Querétaro, San Luis Potosí, Tamaulipas, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-255', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-257', 'Honduras (Colón, Olancho, Yoro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-258', 'Mexico (Chiapas, Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-740', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-259', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-260', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-261', 'Mexico (Sinaloa, Sonora)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-262', 'Mexico (Oaxaca, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-263', 'Mexico (Guerrero, Michoacán)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-265', 'Mexico (Durango, Jalisco, Nayarit, Sinaloa)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-827', 'Mexico (Sonora)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-271', 'South Africa (KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-272', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-273', 'Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-274', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-275', 'Benin (Bergu), Ghana, Nigeria (Plateau), ?Togo', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-276', 'Nigeria (Plateau)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-578', 'Benin (Bergu), Ghana, Nigeria, ?Togo', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-278', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-279', 'Kenya (Narok), Tanzania (Arusha)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-280', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-281', 'South Africa (KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-282', 'Mozambique (Manica), Zimbabwe (Manicaland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-283', 'Zimbabwe (Matabeleland South, Midlands and Masvingo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-284', 'South Africa (Mpumalanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-285', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-286', 'Tanzania (Katavi)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-287', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-288', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-289', 'Uganda (Eastern)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-290', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-293', 'Mozambique (Gaza, Inhambane, Maputo), South Africa (KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-659', 'Mozambique (Inhambane)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-658', 'Mozambique (Gaza, Inhambane, Maputo), South Africa (KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-295', 'South Africa (E Cape, KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-296', 'South Africa (E Cape, KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-298', 'Malawi (Mulanje), Mozambique (Zambézia)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-299', 'South Africa (Mpumalanga), Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-300', 'Kenya (Coast), Tanzania (Lushoto, Tanga, Zanzibar Island)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-302', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-303', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-305', 'South Africa (Mpumalanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-307', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-308', 'Democratic Republic of Congo (Orientale)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-309', 'Tanzania (Morogoro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-310', 'Kenya (Taita-Taveta), Tanzania (Kilimanjaro, ?Morogoro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-312', 'South Africa (E Cape, KwaZulu-Natal, Limpopo, Mpumalanga), Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-313', 'South Africa (Gauteng, Mpumalanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-316', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-317', 'Angola, Democratic Republic of Congo', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-318', 'Mozambique, South Africa (KwaZulu-Natal), Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-319', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-321', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-322', 'South Sudan (Eastern Equatoria)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-323', 'Uganda (Northern)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-324', 'Mozambique (Manica), Zimbabwe', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-326', 'Democratic Republic of Congo (Katanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-328', 'South Africa (Mpumalanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-329', 'South Africa (KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-330', 'Mozambique (Manica)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-332', 'South Africa (KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-333', 'South Africa (KwaZulu-Natal), Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-334', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-335', 'South Africa (Mpumalanga), Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-336', 'Angola (Lunda Sul), Democratic Republic of Congo (Kasai-Occidental, Katanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-337', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-338', 'Mozambique (Manica)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-340', 'Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-341', 'Democratic Republic of Congo (Katanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-342', 'Democratic Republic of Congo (Katanga), Zambia (Luapula, Northern)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-343', 'Tanzania (Tanga)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-344', 'South Africa (KwaZulu-Natal), Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-345', 'Central African Republic, Democratic Republic of Congo (Orientale), South Sudan (Western Equatoria), Uganda (Northern)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-349', 'Kenya (Eastern, Rift Valley)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-350', 'Kenya (Eastern)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-579', 'Kenya (Rift Valley)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-351', 'South Africa (Limpopo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-353', 'South Africa (E Cape)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-354', 'Mozambique (Nampula)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-355', 'Mozambique, Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-358', 'South Africa (E Cape, KwaZulu-Natal), Swaziland', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-360', 'Uganda (Western)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-361', 'South Africa (KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-371', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-372', 'Australia (New South Wales, Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-375', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-376', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-377', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-378', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-380', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-381', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-384', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-385', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-386', 'Australia (WA)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-387', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-388', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-389', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-390', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-391', 'Australia (WA)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-392', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-393', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-395', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-396', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-397', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-398', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-399', 'Australia (New South Wales, Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-400', 'Australia (Northern Territory)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-401', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-403', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-404', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-405', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-406', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-407', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-408', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-410', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-411', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-415', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-416', 'Australia (New South Wales, Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-417', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-419', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-420', 'Australia (WA)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-421', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-422', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-423', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-424', 'Australia (New South Wales)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-425', 'Australia (Queensland)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-427', 'Cuba (Pinar del Río)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-430', 'South Africa (E Cape, KwaZulu-Natal)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-436', 'Costa Rica (San José)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-438', 'Brazil (Amazonas), Colombia, (Amazonas, Vaupés), Ecuador (Morona-Santiago, Napo, Sucumbíos), Peru (Loreto), S Venezuela', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-440', 'Colombia (Valle del Cauca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-441', 'Bahamas (Eleuthera), Cuba (Guantánamo, Oriente, Santiago de Cuba)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-444', 'Bolivia (El Beni, Cochabamba, Santa Cruz), Brazil (Mato Grosso)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-449', 'Colombia (Chocó, Valle del Cauca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-450', 'Mexico (Tabasco)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-451', 'Panama (Colón, Panamá, Kuna de Wargandi, Kuna Yala)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-458', 'Belize (Cayo, Stann Creek, Toledo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-460', 'Colombia (Antioquia)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-461', 'Panama (Colón, Kuna Yala)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-462', 'Panama (Colón, Kuna Yala)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-463', 'Colombia (Santander)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-464', 'Cuba, Jamaica, Puerto Rico', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-465', 'Costa Rica (Puntarenas, San José), Panama (Chiriquí)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-466', 'Mexico (Hidalgo, Querétaro, San Luis Potosí, Tamaulipas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-468', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-471', 'Ecuador (Carchi, Esmeraldas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-472', 'Costa Rica (Limón)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-473', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-476', 'Panama (Bocas del Toro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-477', 'El Salvador (Sonsonate), Guatemala (Quetzaltenango Retalhuleu, Santa Rosa, Suchitepéquez), Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-479', 'Colombia (Huila)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-481', 'Colombia (Amazonas), Peru (Loreto)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-482', 'Panama (Coclé, Colón, Panamá, Veraguas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-483', 'Colombia (Antioquia, Boyacá, Santander)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-484', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-485', 'Bahamas, Cayman Islands, Cuba, United States (Florida, Georgia)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-821', 'United States (Florida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-822', 'United States (Florida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-823', 'United States (Florida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-824', 'United States (Florida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-825', 'United States (Florida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-486', 'Panama (Panamá, Kuna Yala)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-488', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-490', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-496', 'Brazil (Pará), Colombia (Amazonas), Venezuela (Amazonas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-500', 'Ecuador (Azuay, Bolivar, Chimborazo, El Oro, Esmeraldas, Guayas, Los Ríos, Manabi, Pichincha), Perú (Tumbes)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-501', 'Panama (Bocas del Toro, Chiriquí)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-826', 'Colombia (Guaviare)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-502', 'Mexico (Chiapas, Hidalgo, Oaxaca, Tabasco, Tamaulipas, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-507', 'Bahamas (Abaco, Long Island)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-508', 'Peru (Loreto)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-511', 'Colombia (Antioquia, Chocó), Panama (Darién)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-513', 'Belize (Belize, Cayo, Toledo)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-514', 'Colombia (Antioquia, Córdoba, Santander)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-516', 'Colombia (Antioquia, Risaralda)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-517', 'Guatemala (Alta Verapaz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-519', 'Colombia (La Guajira, Meta), Venezuela (Carabobo, Falcón, Guárico, Lara, Miranda, Yaracuy)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-434', 'Panama (Coclé)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-522', 'Panama (Bocas del Toro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-523', 'Costa Rica, Nicaragua (Río San Juan, Atlántico Sur), Panama (Bocas del Toro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-526', 'Colombia (Antioquia, Chocó, Valle del Cauca), Costa Rica (Puntarenas), Panama (Darién, Panamá)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-528', 'Colombia (Risaralda)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-529', 'Honduras (Cortés)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-530', 'Honduras (Atlántida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-533', 'Mexico (Colima, Guerrero, Jalisco, Michoacán, Nayarit, Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-535', 'Brazil (Acre), Peru (Amazonas, Huánuco, Loreto, Pasco, San Martin, Ucayali)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-537', 'W Puerto Rico', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-539', 'Belize (Belize, Cayo, Orange Walk, Stann Creek, Toledo), Guatemala (Petén), Mexico (Campeche, Chiapas, Tabasco, Quintana Roo, Yucatán)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-540', 'Costa Rica (Puntarenas), Panama (Chiriquí)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-541', 'Panama (Bocas del Toro, Coclé, Colón, Veraguas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-542', 'Cuba, Dominican Republic, Puerto Rico', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-544', 'Mexico (Oaxaca, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-545', 'Cuba (W Cuba, Isla de la Juventud)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-546', 'Colombia (Chocó)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-547', 'Colombia (Córdoba)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-548', 'Colombia (Chocó, Nariño, Valle del Cauca), Ecuador (Esmeraldas, Imbabura)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-549', 'Honduras (Atlántida)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-552', 'Panama (Bocas del Toro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-553', 'Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-554', 'Mexico (Oaxaca)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-555', 'Mexico (Chiapas, Tabasco, Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-556', 'Guatemala (Izabal), Honduras (Atlántida, Colón, Cortés, Olancho, Santa Barbara, Yoro)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-557', 'Panama (Panamá)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-558', 'Cuba (Oriente)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-561', 'Colombia (Tolima)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-562', 'Guatemala (Alta Verapaz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-563', 'Bolivia (Pando), Brazil (Acre, Amazonas, Rondônia), Colombia (Amazonas, Caquetá, Guainía, Putumayo, Vaupés), Ecuador (Napo, Pastaza, Sucumbíos), Peru (Loreto, Madre de Dios, Ucayali)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-565', 'Peru (Huánuco)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-566', 'Belize (Toledo), Guatemala (Alta Verapaz, Izabal), Mexico (Chiapas)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-567', 'Mexico (Veracruz)', 'text', null, 163);
INSERT INTO AssemblyDB.distribution (record_id, name_code, distribution, StandardInUse, DistributionStatus, database_id) VALUES (null, 'Cyd-8', 'Colombia (Antioquia)', 'text', null, 163);